### ISSUE TITLE
Facing issues to install the repository with Conda

### ISSUE THREAD

**Issue by ajbanegas** [PaccMann/paccmann_datasets#62] opened 2020-07-03 10:51 UTC
Hi, I'm following the instructions written in README.md to install pytoda with Conda but it still fails.
When I run the command:

$ conda env create -f conda.yml

I get the following message:

Could not find a version that satisfies the requirement rdkit==2019.03.1 (from -r /home/biohpc/paccmann_datasets/condaenv.5xlin6py.requirements.txt (line 1)) (from versions: )
No matching distribution found for rdkit==2019.03.1 (from -r /home/biohpc/paccmann_datasets/condaenv.5xlin6py.requirements.txt (line 1))

I also face similar issues with other packages, e.g. torch==1.0.1 does not exist, the latest available version is 0.1.2.post2.
To overcome these sort of problem I tried to change the versions in conda.yml but I didn't succeed.

Some similar happens when installing paccmann_predictor.
Could you help me install the repositories to make predictions?

Thanks
![Captura de pantalla de 2020-07-03 11-00-13](https://user-images.githubusercontent.com/67786260/86462352-c71c8580-bd2b-11ea-97a3-e6d0fb4ed2b3.png)

**Comment by drugilsberg** [comment] 2020-07-03 12:26
Hi @ajbanegas thanks for opening the issue.
Just to clarify, this was obtained by running the environment creation from the predictor repo.

Could you try cloning paccmann_datasets and run the installation as follows:

```console
git clone https://github.com/PaccMann/paccmann_datasets.git
cd paccmann_datasets
conda env create -f conda.yml
conda activate pytoda
python -c "import pytoda"
```

and paster the error if any?

Also, could you also specify OS and architecture (powerpc/intel/etc.)?

**Comment by ajbanegas** [comment] 2020-07-03 15:38
Hi @drugilsberg,

I follow all the steps in a brand new virtual machine and it worked perfectly. Next, I also checked out and installed paccmann_predictor and it worked too. However, I can't run the examples/train_paccmann.py because I get the error showed in attachment.
![Captura de pantalla de 2020-07-03 17-32-13](https://user-images.githubusercontent.com/67786260/86483056-80db1c80-bd53-11ea-8726-1d8fd7a0e687.png)

This is running on a VirtualBox machine with:
Python 3.7.7
conda 4.8.3 (Miniconda)
Ubuntu 18.04.4 LTS (Bionic Beaver) x86_64
kernel 4.15.0-109-generic

Anyway, my question now is: how can I make a prediction now? I assume I can take the test or validation files from the repo described in the paper and run a script, but still not totally clear for me.

In case the train_paccmann.py script should work, that would be the first issue to address.

Best

**Comment by drugilsberg** [comment] 2020-07-04 06:51
HI @ajbanegas great to hear that.

I think what you observe it's an issue in the VM configuration. Can you check/install libXrender?

```console
apt-get install libfontconfig1 libxrender1
```

Regarding running predictions, there is no need to use the files linked in the paper, feel free to use the ones linked in the repo, available [here](https://ibm.box.com/v/paccmann-pytoda-data).

**Comment by ajbanegas** [comment] 2020-07-06 09:54
Thanks @drugilsberg, it works perfect now once installed these packages.

Sorry to bother you again with this, but I still don't get how predictions can be carried out. My only aim is to reproduce the table publised in "Toward Explainable Anticancer Compound Sensitivity Prediction via Multimodal Attention-Based Convolutional Encoders" including the different models, but, to my understanding, the script train_paccmann.py is meant to train a model. If I'm not wrong, I have to run it and make a small script to load the saved model and use it to run predictions. Is it correct?
I just want to reproduce the results by running something but still not clear for me what to run and what are the files.

Best

**Comment by drugilsberg** [comment] 2020-07-06 10:00
Hi @ajbanegas,

no problem at all, my pleasure to help researches interested in our work.
You got it right. You just need to load the saved model and feed the data to it in a script.
Basically this section of `train_paccmann.py` will serve the purpose:

```python
# Measure validation performance
        model.eval()
        with torch.no_grad():
            test_loss = 0
            predictions = []
            labels = []
            for ind, (smiles, gep, y) in enumerate(test_loader):
                y_hat, pred_dict = model(
                    torch.squeeze(smiles.to(device)), gep.to(device)
                )
                predictions.append(y_hat)
                labels.append(y)
                loss = model.loss(y_hat, y.to(device))
                test_loss += loss.item()

        predictions = np.array(
            [p.cpu() for preds in predictions for p in preds]
        )
        labels = np.array([l.cpu() for label in labels for l in label])
        test_pearson_a = pearsonr(
            torch.Tensor(predictions), torch.Tensor(labels)
        )
        test_rmse_a = np.sqrt(np.mean((predictions - labels)**2))
        test_loss_a = test_loss / len(test_loader)
        logger.info(
            f"\t **** TESTING **** Epoch [{epoch + 1}/{params['epochs']}], "
            f"loss: {test_loss_a:.5f}, "
            f"Pearson: {test_pearson_a:.3f}, "
            f"RMSE: {test_rmse_a:.3f}"
        )
```

after loading the data and the model (in the beginning of the script you have the example).

A word of advice the paper you referenced was using a tensorflow version of the code and the best results reported are obtained via model ensembling. The results you will obtain from the best single model we provide in torch will differ.
Anyhow, this is exactly the same model we have deployed in the web service.

**Comment by ajbanegas** [comment] 2020-07-06 16:44
Thank you again @drugilsberg. Next (and hopefully last) question. Could you confirm that my command-line test is correct, please? I'm being told that the number of samples is 0, so I'm afraid I did make another mistake somewhere.
![VirtualBox_REVERT_06_07_2020_18_37_54](https://user-images.githubusercontent.com/67786260/86618146-b2085680-bfb8-11ea-8f0b-a43d7d89b1bf.png)

**Comment by drugilsberg** [comment] 2020-07-06 17:02
The command line looks good to me. This might be due to the recent updates in the `pytoda` package.
@jannisborn and @C-nit, can you think of anything that is causing the number of samples to be zero in the dataset classes referenced in the predictor training [script](https://github.com/PaccMann/paccmann_predictor/blob/master/examples/train_paccmann.py)?

**Comment by jannisborn** [comment] 2020-07-06 21:00
@ajbanegas Sorry for the inconvenience and thanks for the interest in our work.
The above error is caused by inconsistent nomenclature between the files. The `gdsc_cell_line_ic50_...` files have the cell lines indexed via their plain name and so does `gdsc-rnaseq_gene-expression.csv` that you find under the same source as the RMA file that you use. The RMA file instead uses the COSMIC IDs to index the cell lines. This is why in the shared folder under `data/drug_sensitivity` we have two files, one for COSMIC ID and one for cell line name. 

If you want to use the RMA data as in your above code, split `gdsc-cosmic-id_drug-sensitivity.csv` yourself into train/test and feed these ones to `train_paccmann.py` as above. 

If this does not work, please let us know.

**Comment by ajbanegas** [comment] 2020-07-07 15:03
I did split the .csv file into two separate files and now I get this (see attachment).
![VirtualBox_REVERT_07_07_2020_13_23_04](https://user-images.githubusercontent.com/67786260/86800463-56e76a00-c073-11ea-847d-6b663299658a.png)

It seems that the column 'drug' is missing somewhere. 
The command looks like this now:

python ./examples/train_paccmann.py \
../paccmann_paper_data/my_rma_train.csv \
../paccmann_paper_data/my_rma_test.csv \
../paccmann_paper_data/gene_expression/gdsc-rma_gene-expression.csv \
../paccmann_paper_data/smiles/gdsc.smi \
../paccmann_paper_data/2128_genes.pkl \
../paccmann_paper_data/smiles_language_chembl_gdsc_ccle.pkl \
../EMPTY-DIR \
./examples/example_params.json \
mca

**Comment by jannisborn** [comment] 2020-07-07 15:40
Are you sure that your created files `my_rma_train.csv` and `my_rma_test.csv` include a column called `drug`?

**Comment by C-nit** [comment] 2020-07-07 15:52
Hi @ajbanegas, 
The error suggests that either `train_sensitivity_filepath` (i.e. my_rma_train.csv) or `test_sensitivity_filepath` (i.e. my_rma_test.csv) is missing the "drug" column. Maybe one of the files does not have a header with column names after the split?

for completeness:
>supported format is .csv, with an index and three header columns named: "drug", "cell_line", "IC50"

**Comment by ajbanegas** [comment] 2020-07-07 16:18
You're totally right, I forgot to add the header in the test file.
But I still must be doing something wrong because I get a "ZeroDivisionError: division by zero" in line 254. I already faced this issue today and I managed to find that len(train_loader) == 0.
Could it be related with the fact that I only take 499 training samples and 99 test samples to avoid running out of memory?

**Comment by jannisborn** [comment] 2020-07-07 16:21
exactly. Since `drop_last` is set to True in the script and the default batch size is 2048, both your loaders will be empty: https://github.com/PaccMann/paccmann_predictor/blob/0b9ca9994813292210150f1dd9303f909c70f5c6/examples/train_paccmann.py#L169

**Comment by C-nit** [comment] 2020-07-09 16:43
Hey @ajbanegas, in case you can't or don't want to increase the memory for your virtual machine, you can change the batch size parameter via the json file passed as `params_filepath`.
So you could simply modify the line 
```json
    "batch_size": 2048,
```
in `./examples/example_params.json` or use a modified copy of it with the training script.
This way, you can use the full dataset and try different values for the batch size to not run out of memory.

**Comment by jannisborn** [comment] 2020-07-12 22:00
Closing this issue since it seems resolved. Please reopen if applicable.

**Closed as completed by jannisborn** 2020-07-12 22:00 UTC
